#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
D="$ROOT/safebox-desktop"
python3 -m py_compile "$D/scripts/web_browser_cdp_e2e.py"
bash -n "$D/scripts/web_browser_e2e.sh"
python3 "$D/scripts/web_production_check.py"
python3 "$D/scripts/web_foundation_check.py"
python3 "$D/scripts/desktop_cross_platform_audit.py"
"$ROOT/verification/verify_v027_ios_archive_passthrough_r39.sh"
"$ROOT/verification/verify_v027_ios_gma_link_scope_r41.sh"
"$ROOT/verification/verify_v027_ios_ads_runtime_session_r42.sh"
grep -qx 'v0.2.8-web-browser-progress-timeout-r79-20260831A' "$ROOT/SAFEBOX_V028_PACKAGE_ID.txt"
! grep -q -- '--virtual-time-budget' "$D/scripts/web_browser_e2e.sh"
! grep -q -- '--dump-dom' "$D/scripts/web_browser_e2e.sh"
grep -q 'SAFEBOX_WEB_BROWSER_E2E_HEARTBEAT' "$D/scripts/web_browser_cdp_e2e.py"
grep -q 'SAFEBOX_WEB_BROWSER_E2E_TIMEOUT_FAIL' "$D/scripts/web_browser_cdp_e2e.py"
grep -q 'SAFEBOX_WEB_BROWSER_E2E_EARLY_EXIT_PASS' "$D/scripts/web_browser_cdp_e2e.py"
grep -q 'runBrowserE2E(emitMarker)' "$D/src/web-e2e.ts"
echo "SAFEBOX_V028_WEB_BROWSER_PROGRESS_TIMEOUT_R79_VERIFY_PASS"
